<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDetalle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle');
        $this->hasColumn('id_producto', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cantidad', 'integer', null, array(
             'type' => 'integer',
             'default' => '1',
             ));
        $this->hasColumn('id_pedido', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Producto', array(
             'local' => 'id_producto',
             'foreign' => 'id'));

        $this->hasOne('Pedido', array(
             'local' => 'id_pedido',
             'foreign' => 'id'));
    }
}