<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePedido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pedido');
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('id_estado', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_restaurant', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Detalle', array(
             'local' => 'id',
             'foreign' => 'id_pedido'));

        $this->hasOne('EstadoPedido as Estado', array(
             'local' => 'id_estado',
             'foreign' => 'id'));

        $this->hasMany('Mesa', array(
             'local' => 'id',
             'foreign' => 'id_pedido'));

        $this->hasOne('Restaurant', array(
             'local' => 'id_restaurant',
             'foreign' => 'id'));
    }
}