<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseFactura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('factura');
        $this->hasColumn('numero', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('propina', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('id_mesa', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_caja', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('total', 'float', null, array(
             'type' => 'float',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Mesa', array(
             'local' => 'id_mesa',
             'foreign' => 'id'));

        $this->hasOne('Caja', array(
             'local' => 'id_caja',
             'foreign' => 'id'));
    }
}