<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePrueba extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('prueba');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

}