<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRestaurant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('restaurant');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Mesa as Mesas', array(
             'local' => 'id',
             'foreign' => 'id_restaurant'));

        $this->hasMany('Mozo as Mozos', array(
             'local' => 'id',
             'foreign' => 'id_restaurant'));

        $this->hasMany('Producto as Productos', array(
             'local' => 'id',
             'foreign' => 'id_restaurant'));

        $this->hasMany('EstadoMesa as MesaEstados', array(
             'local' => 'id',
             'foreign' => 'id_restaurant'));

        $this->hasMany('EstadoPedido as PedidoEstados', array(
             'local' => 'id',
             'foreign' => 'id_restaurant'));

        $this->hasMany('EstadoCaja as CajaEstados', array(
             'local' => 'id',
             'foreign' => 'id_restaurant'));

        $this->hasMany('Pedido as Pedidos', array(
             'local' => 'id',
             'foreign' => 'id_restaurant'));
    }
}