<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCaja extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('caja');
        $this->hasColumn('id_factura', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fecha_abierta', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fecha_cerrada', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('id_estado', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Factura as Facturas', array(
             'local' => 'id',
             'foreign' => 'id_caja'));

        $this->hasOne('EstadoCaja as Estado', array(
             'local' => 'id_estado',
             'foreign' => 'id'));
    }
}