<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/02 00:49:09

return array(
'restaurant' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=restaurant',
  'username' => 'root',
  'password' => NULL,
  'name' => 'restaurant',
)),);
