<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoPedido extends BaseEstadoPedido implements JsonSerializable
{
	const PENDIENTE = 'PEN';
	const ENTREGADO = 'ENT';
	
	/**
	 * busca por codigo y devuelve el estado "abierta"
	 *
	 * @return string
	 */
	public static function pendiente() {
		return Restaurant::getInstance()->estadosPedido()->findByProperty('codigo', self::PENDIENTE);
	}
	
	/**
	 * busca por codigo y devuelve el estado "cerrada"
	 *
	 * @return string
	 */
	public static function entregado() {
		return Restaurant::getInstance()->estadosPedido()->findByProperty('codigo', self::ENTREGADO);
	}
	
	public function getJson($type = '') {
		$json = new JsonObject();
		$json
			->withValue('id', $this->getId())
			->withValue('codigo', $this->getCodigo())
			->withValue('nombre', $this->getNombre());
		return $json;
	}
}