<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoCaja extends BaseEstadoCaja
{
	const ABIERTA = 'AB';
	const CERRADA = 'CE';
	
	/**
	 * busca por codigo y devuelve el estado "abierta"
	 *
	 * @return string
	 */
	public static function abierta() {
		return Restaurant::getInstance()->estadosCaja()->findByProperty('codigo', self::ABIERTA);
	}
	
	/**
	 * busca por codigo y devuelve el estado "cerrada"
	 *
	 * @return string
	 */
	public static function cerrada() {
		return Restaurant::getInstance()->estadosCaja()->findByProperty('codigo', self::CERRADA);
	}
}