<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mozo extends BaseMozo implements JsonSerializable
{
	public function getNombreCompleto() {
		return $this->getNombre()." ".$this->getApellido();
	}
	
	public function getJson($type = '') {
		$json = new JsonObject();
		$json
			->withValue('id', $this->getId())
			->withValue('nombre', $this->getNombre())
			->withValue('apellido', $this->getApellido());
			
		return $json;
		
	}
}